AWSTemplateFormatVersion: '2010-09-09'
Description: ALB Nested Stack - Internet-facing Application Load Balancer
Resources:
  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-templates-bucket/templates/alb.yaml
      Parameters:
        Environment: dev
        VpcId: vpc-0abc1234def567890 # Replace with actual VPC ID
        PublicSubnet1: subnet-0123456789abcdef0 # Replace with actual Public Subnet 1 ID
        PublicSubnet2: subnet-0fedcba9876543210 # Replace with actual Public Subnet 2 ID
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation