AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nested ECR Repository for Docker Images'
Resources:
  FunctionManagerECRStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/cf-templates-bucket/templates/ecr.yaml
      Parameters:
        ApplicationName: function-manager
        Environment: dev
      Tags:
        - Key: Name
          Value: function-manager-ecr
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation
  AcquiflowECRStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/cf-templates-bucket/templates/ecr.yaml
      Parameters:
        ApplicationName: acquiflow
        Environment: dev
      Tags:
        - Key: Name
          Value: acquiflow-ecr
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation
