Description: Master Stack - ECS Service
Resources:
  ECSServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: TargetGroupStack
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-cfn-templates-bucket/templates/ecs-service.yaml
      Parameters:
        Environment:          dev
        AppName:              myapp
        ECSClusterName:       my-existing-ecs-cluster
        TaskDefinitionArn:    !GetAtt TaskDefDoubleStack.Outputs.TaskDefinitionArn
        # TaskDefinitionArn:  !GetAtt TaskDefSingleStack.Outputs.TaskDefinitionArn   # swap if using single
        TargetGroupArn:       !GetAtt TargetGroupStack.Outputs.TargetGroupArn
        ContainerName:        nginx    # change to rails if using single container
        ContainerPort:        80       # change to 3000 if using single container
        DesiredCount:         1
        ScalingMinCapacity:   1
        ScalingMaxCapacity:   4
        CPUScaleOutThreshold: 70
        CPUScaleInThreshold:  30
        MemoryScaleOutThreshold: 75
        MemoryScaleInThreshold:  40
Outputs:
  ServiceArn:   
    Description: ARN of the ECS Service
    Value: !GetAtt ECSServiceStack.Outputs.ServiceArn
  ServiceName:
    Description: Name of the ECS Service
    Value: !GetAtt ECSServiceStack.Outputs.ServiceName