AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Nested Stack - ECS Cluster backed by EC2 ASG (t4g.small, min/max/desired=1)
Resources:
  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-templates-bucket/templates/ecs.yaml
      Parameters:
        Environment: dev
        VpcId: vpc-0abc1234def567890
        PrivateSubnet1: subnet-0aaa1111bbb22222
        PrivateSubnet2: subnet-0ccc3333ddd44444
        KeyPairName: dev-ecs-keypair
        InstanceType: t4g.small
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation
Outputs:
  ECSClusterName:
    Description: ECS Cluster Name
    Value: !GetAtt ECSStack.Outputs.ECSClusterName