AWSTemplateFormatVersion: '2010-09-09'
Description: Master Stack - IAM Execution Role
Resources:
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-cfn-templates-bucket/templates/iam-execution.yaml
      Parameters:
        Environment: dev
        AppName:     myapp
Outputs:
  ExecutionRoleArn:
    Value: !GetAtt IAMStack.Outputs.ExecutionRoleArn
