AWSTemplateFormatVersion: '2010-09-09'
Description: Master Stack - IAM Task Role

Resources:
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-cfn-templates-bucket/templates/iam-task.yaml
      Parameters:
        Environment: dev
        AppName:     myapp

        # ── Task Role Policy ─────────────────────────────────────────────────
        # Full IAM policy JSON — add/remove statements as needed
        TaskRolePolicyJson: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "S3AppAccess",
                "Effect": "Allow",
                "Action": [
                  "s3:GetObject",
                  "s3:PutObject",
                  "s3:DeleteObject",
                  "s3:ListBucket"
                ],
                "Resource": [
                  "arn:aws:s3:::dev-myapp-assets",
                  "arn:aws:s3:::dev-myapp-assets/*"
                ]
              },
              {
                "Sid": "SSMParameterRead",
                "Effect": "Allow",
                "Action": [
                  "ssm:GetParameter",
                  "ssm:GetParameters",
                  "ssm:GetParametersByPath"
                ],
                "Resource": "arn:aws:ssm:us-east-1:123456789012:parameter/dev/myapp/*"
              },
              {
                "Sid": "CloudWatchLogs",
                "Effect": "Allow",
                "Action": [
                  "logs:CreateLogStream",
                  "logs:PutLogEvents"
                ],
                "Resource": "arn:aws:logs:us-east-1:123456789012:log-group:/ecs/dev/myapp:*"
              },
              {
                "Sid": "SecretsManagerRead",
                "Effect": "Allow",
                "Action": [
                  "secretsmanager:GetSecretValue"
                ],
                "Resource": "arn:aws:secretsmanager:us-east-1:123456789012:secret:dev/myapp/*"
              }
            ]
          }
Outputs:
  TaskRoleArn:
    Value: !GetAtt IAMStack.Outputs.TaskRoleArn