Description: Main CloudFormation template for provisioning AWS infrastructure for Rails application using Terraform.
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TaskDefSingleStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-cfn-templates-bucket/templates/rails-tf.yaml
      Parameters:
        Environment:        dev
        AppName:            myapp
        RailsImage:         123456789012.dkr.ecr.us-east-1.amazonaws.com/myapp-rails:latest
        RailsContainerPort: 3000
        TaskCPU:            512
        TaskMemory:         1024
        TaskRoleArn:        !GetAtt IAMStack.Outputs.TaskRoleArn
        ExecutionRoleArn:   !GetAtt IAMStack.Outputs.ExecutionRoleArn
Outputs:
  TaskDefArn:
    Description: ARN of the ECS Task Definition
    Value: !GetAtt TaskDefSingleStack.Outputs.TaskDefArn