AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Stack - function-manager application bucket

Resources:
  FunctionManagerS3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/s3.yaml
      Parameters:
        Environment: dev
        AppName: function-manager
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation

  AcquiflowS3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/s3.yaml
      Parameters:
        Environment: dev
        AppName: acquiflow
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation

