AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager Nested Stack - Application secrets for dev environment
SecretsManagerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-cfn-templates-bucket/templates/secretsmanager.yaml
      Parameters:
        Environment: dev
        AppName:     myapp
        SecretValue: |
          {
            "DATABASE_URL":      "postgres://user:pass@mydb.rds.amazonaws.com:5432/myapp_dev",
            "REDIS_URL":         "redis://myelasticache.cache.amazonaws.com:6379/0",
            "RAILS_MASTER_KEY":  "abc123yourmasterkey",
            "SECRET_KEY_BASE":   "abc123yoursecretkeybase",
            "S3_BUCKET_NAME":    "dev-myapp-assets",
            "SMTP_PASSWORD":     "your-smtp-password"
          }
