AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager Stack - All app secrets

Resources:
  FunctionManagerSecretStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/secret-manager.yaml
      Parameters:
        Environment: dev
        AppName: function-manager
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation

  AcquiflowSecretStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/secret-manager.yaml
      Parameters:
        Environment: dev
        AppName: acquiflow
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation
