AWSTemplateFormatVersion: '2010-09-09'
Description: Infra Stack - Main stack to orchestrate nested stacks for VPC, ALB, ECS Cluster, IAM Roles, S3, ECR, and Secrets Manager
Resources:
  #---- 1. ALB ------------------------------------------------------------
  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/alb.yaml
      Parameters:
        Environment: dev
        VpcId: '{{resolve:ssm:/cfn/vpc/VpcId}}'
        PublicSubnet1: '{{resolve:ssm:/cfn/vpc/PublicSubnet1}}'
        PublicSubnet2: '{{resolve:ssm:/cfn/vpc/PublicSubnet2}}'
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation 

  #---- 2. ECS Cluster ---------------------------------------------------------
  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/ecs.yaml
      Parameters:
        Environment: dev
        VpcId: '{{resolve:ssm:/cfn/vpc/VpcId}}'
        PrivateSubnet1: '{{resolve:ssm:/cfn/vpc/PrivateSubnet1}}'
        PrivateSubnet2: '{{resolve:ssm:/cfn/vpc/PrivateSubnet2}}'
        KeyPairName: dev-ecs-keypair
        InstanceType: m7i-flex.large
        ALBSecurityGroup: !GetAtt ALBStack.Outputs.ALBSecurityGroupId
        ALBTargetGroupArn: !GetAtt ALBStack.Outputs.ALBTargetGroupArn
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation

  #---- 3. IAM Execution Role ------------------------------------------------------------
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/iam-execution.yaml
      Parameters:
        Environment: dev
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation

  #---- 4. S3 ------------------------------------------------------------ 
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/s3.yaml
      Parameters:
        Environment: dev
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation

  #---- 5. IAM Task Role ----------------------------------------------------------
  IAMTaskStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/iam-task.yaml
      Parameters:
        Environment: dev
      Tags:
        - Key: Environment
          Value: dev    
        - Key: ManagedBy
          Value: CloudFormation

  #---- 6. Target Group ------------------------------------------------------------
  TargetGroupStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ALBStack
    Properties: 
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/target-group.yaml
      Parameters:
        Environment: dev
        VpcId: '{{resolve:ssm:/cfn/vpc/VpcId}}'
        ALBHTTPListenerArn: !GetAtt ALBStack.Outputs.ALBHTTPListenerArn
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation  

  #---- 7. Function Manager ECR Repository ---------------------------------------
  FunctionManagerECRStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/ecr.yaml
      Parameters:
        Environment: dev
        RepoName: function-manager        
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation
    
  #---- ECR: acquiflow ------------------------------------------------------------
  AcquiflowECRStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/ecr.yaml
      Parameters:
        Environment: dev
        RepoName: acquiflow               # ← Creates dev-acquiflow
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation

  #---- 8. Secret Manager ------------------------------------------------------------
  SecretsManagerStack:
    Type: AWS::CloudFormation::Stack  
    Properties: 
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/secret-manager.yaml
      Parameters:
        Environment: dev
      Tags:
        - Key: Environment
          Value: dev    
        - Key: ManagedBy
          Value: CloudFormation 
Outputs:
  ECSClusterName:
    Description: ECS Cluster Name
    Value: !GetAtt ECSStack.Outputs.ECSClusterName
  ExecutionRoleArn:
    Description: IAM Execution Role ARN
    Value: !GetAtt IAMStack.Outputs.ExecutionRoleArn
    

    