AWSTemplateFormatVersion: '2010-09-09'
Description: ALB Nested Stack - Internet-facing Application Load Balancer
Resources:
  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/alb.yaml
      Parameters:
        Environment: dev
        VpcId: vpc-04c6d87c521fddb25 # Replace with actual VPC ID
        PublicSubnet1: subnet-0fc41a16b6ecbb14d # Replace with actual Public Subnet 1 ID
        PublicSubnet2: subnet-0f520177833df3f2e # Replace with actual Public Subnet 2 ID
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation

#---------------------------------------------------------------

  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/ecs.yaml
      Parameters:
        Environment: dev
        VpcId: vpc-04c6d87c521fddb25
        PrivateSubnet1: subnet-0eabd0999a1e9300b
        PrivateSubnet2: subnet-03f8f438576701c78
        KeyPairName: dev-ecs-keypair
        InstanceType: t4g.small
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation

#---------------------------------------------------------------

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/iam-execution.yaml
      Parameters:
        Environment: dev
        AppName: myapp

#---------------------------------------------------------------

Outputs:
  ECSClusterName:
    Description: ECS Cluster Name
    Value: !GetAtt ECSStack.Outputs.ECSClusterName
  ExecutionRoleArn:
    Description: IAM Execution Role ARN
    Value: !GetAtt IAMStack.Outputs.ExecutionRoleArn
