Description: CloudFormation Stack for Target Group
AWSTemplateFormatVersion: '2010-09-09'  
Resources:
  TargetGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-cfn-templates-bucket/templates/target-group.yaml
      Parameters:
        Environment:    dev
        AppName:        myapp
        VpcId:          vpc-0abc123456789def0
        ALBListenerArn: arn:aws:elasticloadbalancing:us-east-1:123456789012:listener/app/my-alb/abc123/def456
        HostHeader:     myapp.example.com
        TargetPort:     80              # 80 for double (nginx), 3000 for single (rails)
Outputs:
  TargetGroupArn:
    Description: Target Group ARN
    Value: !GetAtt TargetGroupStack.Outputs.TargetGroupArn