AWSTemplateFormatVersion: '2010-09-09'
Description: Target Group Stack - Host-header listener rules for all services

Resources:
  TargetGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/target-group.yaml
      Parameters:
        Environment: dev
        VpcId: '{{resolve:ssm:/cfn/vpc/VpcId}}'
        ALBHTTPListenerArn: '{{resolve:ssm:/cfn/dev/alb/HTTPListenerArn}}'
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation