AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Nested CloudFormation Stack - Dev Environment
  Orchestrates: VPC, ECS Cluster with EC2 ASG, ALB, S3 and ECR resources for development environment
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-templates-bucket/templates/vpc.yaml
      Parameters:
        Environment: dev
        VpcCidr: 10.0.0.0/16
        PublicSubnet1Cidr: 10.0.1.0/24
        PublicSubnet2Cidr: 10.0.2.0/24
        PrivateSubnet1Cidr: 10.0.3.0/24
        PrivateSubnet2Cidr: 10.0.4.0/24
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation
Outputs:
  VpcId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VpcId