AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild project for app

Parameters:
  ProjectName:
    Type: String
  ServiceRoleArn:
    Type: String
  SourceRepoUrl:
    Type: String
  SourceBranch:
    Type: String
  ArtifactsBucket:
    Type: String
  EnvironmentImage:
    Type: String
    Default: "aws/codebuild/standard:7.0"

Resources:
  AppCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      ServiceRole: !Ref ServiceRoleArn
      Artifacts:
        Type: S3
        Location: !Ref ArtifactsBucket
        Packaging: ZIP
        Name: !Sub "${ProjectName}-artifacts"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref EnvironmentImage
        PrivilegedMode: true
      Source:
        Type: GITHUB
        Location: !Ref SourceRepoUrl
        GitCloneDepth: 1
        BuildSpec: "buildspec.yml"
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: !Sub "refs/heads/${SourceBranch}"
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Sub "/codebuild/${ProjectName}"
          StreamName: "build"
