AWSTemplateFormatVersion: '2010-09-09'
Description: ECR repository for an app

Parameters:
  RepositoryName:
    Type: String
    Description: Name of the ECR repository

Resources:
  AppRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryName:
    Value: !Ref AppRepository
    Description: Name of the ECR repository

  RepositoryArn:
    Value: !GetAtt AppRepository.Arn
    Description: ARN of the ECR repository
