AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR Repository for Docker Images'

Parameters:
  Environment:
    Type: String
    Description: Environment name
  
  ApplicationName:
    Type: CommaDelimitedList
    Description: Name of the application
  
  ImageTagMutability:
    Type: String
    Description: The tag mutability setting for the repository
    AllowedValues:
      - MUTABLE
      - IMMUTABLE
    Default: MUTABLE
  
  ScanOnPush:
    Type: String
    Description: Enable image scanning on push
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  
  LifecyclePolicyText:
    Type: String
    Description: JSON lifecycle policy for ECR
    Default: |
      {
        "rules": [
          {
            "rulePriority": 1,
            "description": "Keep last 20 images",
            "selection": {
              "tagStatus": "any",
              "countType": "imageCountMoreThan",
              "countNumber": 20
            },
            "action": {
              "type": "expire"
            }
          }
        ]
      }

Resources:
  ECRRepository0:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Select [0, !Ref ApplicationName]
      ImageTagMutability: !Ref ImageTagMutability
      ImageScanningConfiguration:
        ScanOnPush: !Ref ScanOnPush
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicyText
      Tags:
        - Key: Name
          Value: !Select [1, !Ref ApplicationName]
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: ManagedBy
          Value: CloudFormation

  ECRRepository1:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Select [1, !Ref ApplicationName]
      ImageTagMutability: !Ref ImageTagMutability
      ImageScanningConfiguration:
        ScanOnPush: !Ref ScanOnPush
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicyText
      Tags:
        - Key: Name
          Value: !Select [1, !Ref ApplicationName]
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  RepositoryName:
    Description: Name of the ECR Repository
    Value: !Ref ECRRepository0
    Export:
      Name: !Sub '${AWS::StackName}-RepositoryName0'

  RepositoryName1:
    Description: Name of the ECR Repository 1
    Value: !Ref ECRRepository1
    Export:
      Name: !Sub '${AWS::StackName}-RepositoryName1'