AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Service Stack - EC2 launch type with CPU and Memory Service Auto Scaling

Parameters:
  Environment:
    Type: String
  AppName:
    Type: String
  ECSClusterName:
    Type: String
  TaskDefinitionArn:
    Type: String
  TargetGroupArn:
    Type: String
  ContainerName:
    Type: String
    Description: Container name to register with the target group (nginx or rails)
  ContainerPort:
    Type: Number
    Default: 80

  # Service sizing
  DesiredCount:
    Type: Number
    Default: 1

  # Auto Scaling bounds
  ScalingMinCapacity:
    Type: Number
    Default: 1
  ScalingMaxCapacity:
    Type: Number
    Default: 4

  # CPU scale-out threshold (%)
  CPUScaleOutThreshold:
    Type: Number
    Default: 70
  CPUScaleInThreshold:
    Type: Number
    Default: 30

  # Memory scale-out threshold (%)
  MemoryScaleOutThreshold:
    Type: Number
    Default: 75
  MemoryScaleInThreshold:
    Type: Number
    Default: 40

Resources:

  # ── ECS Service ────────────────────────────────────────────────────────────
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${Environment}-${AppName}-service
      Cluster: !Ref ECSClusterName
      TaskDefinition: !Ref TaskDefinitionArn
      LaunchType: EC2
      DesiredCount: !Ref DesiredCount
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
        MaximumPercent: 200
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroupArn
      HealthCheckGracePeriodSeconds: 60
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-${AppName}-service
        - Key: Environment
          Value: !Ref Environment

  # ── Auto Scaling — IAM Role ────────────────────────────────────────────────
  ServiceAutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Environment}-${AppName}-autoscaling-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: application-autoscaling.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole

  # ── Scalable Target ────────────────────────────────────────────────────────
  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: ECSService
    Properties:
      MaxCapacity: !Ref ScalingMaxCapacity
      MinCapacity: !Ref ScalingMinCapacity
      ResourceId: !Sub service/${ECSClusterName}/${Environment}-${AppName}-service
      RoleARN: !GetAtt ServiceAutoScalingRole.Arn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  # ── Scale Out Policy — CPU ─────────────────────────────────────────────────
  CPUScaleOutPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ${Environment}-${AppName}-cpu-scale-out
      PolicyType: StepScaling
      ScalingTargetId: !Ref ScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 120
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            MetricIntervalUpperBound: 20
            ScalingAdjustment: 1
          - MetricIntervalLowerBound: 20
            ScalingAdjustment: 2

  CPUScaleOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Environment}-${AppName}-cpu-high
      AlarmDescription: Scale out when CPU > threshold
      Namespace: AWS/ECS
      MetricName: CPUUtilization
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSClusterName
        - Name: ServiceName
          Value: !Sub ${Environment}-${AppName}-service
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: !Ref CPUScaleOutThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref CPUScaleOutPolicy

  # ── Scale In Policy — CPU ──────────────────────────────────────────────────
  CPUScaleInPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ${Environment}-${AppName}-cpu-scale-in
      PolicyType: StepScaling
      ScalingTargetId: !Ref ScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 300
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalUpperBound: 0
            ScalingAdjustment: -1

  CPUScaleInAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Environment}-${AppName}-cpu-low
      AlarmDescription: Scale in when CPU < threshold
      Namespace: AWS/ECS
      MetricName: CPUUtilization
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSClusterName
        - Name: ServiceName
          Value: !Sub ${Environment}-${AppName}-service
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: !Ref CPUScaleInThreshold
      ComparisonOperator: LessThanOrEqualToThreshold
      AlarmActions:
        - !Ref CPUScaleInPolicy

  # ── Scale Out Policy — Memory ──────────────────────────────────────────────
  MemoryScaleOutPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ${Environment}-${AppName}-memory-scale-out
      PolicyType: StepScaling
      ScalingTargetId: !Ref ScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 120
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            ScalingAdjustment: 1

  MemoryScaleOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Environment}-${AppName}-memory-high
      AlarmDescription: Scale out when Memory > threshold
      Namespace: AWS/ECS
      MetricName: MemoryUtilization
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSClusterName
        - Name: ServiceName
          Value: !Sub ${Environment}-${AppName}-service
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: !Ref MemoryScaleOutThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref MemoryScaleOutPolicy

  # ── Scale In Policy — Memory ───────────────────────────────────────────────
  MemoryScaleInPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ${Environment}-${AppName}-memory-scale-in
      PolicyType: StepScaling
      ScalingTargetId: !Ref ScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 300
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalUpperBound: 0
            ScalingAdjustment: -1

  MemoryScaleInAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Environment}-${AppName}-memory-low
      AlarmDescription: Scale in when Memory < threshold
      Namespace: AWS/ECS
      MetricName: MemoryUtilization
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSClusterName
        - Name: ServiceName
          Value: !Sub ${Environment}-${AppName}-service
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: !Ref MemoryScaleInThreshold
      ComparisonOperator: LessThanOrEqualToThreshold
      AlarmActions:
        - !Ref MemoryScaleInPolicy

Outputs:
  ECSServiceName:
    Description: ECS Service Name
    Value: !GetAtt ECSService.Name
    Export:
      Name: !Sub ${AWS::StackName}-ECSServiceName

  ScalableTargetId:
    Description: Auto Scaling Target Resource ID
    Value: !Sub service/${ECSClusterName}/${Environment}-${AppName}-service