AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 Bucket Creation

Parameters:
  BucketName:
    Type: String
    Default: my-simple-cloudformation-bucket-1202027
    Description: s3 bucket name to be created
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket

  BucketArn:
    Description: ARN of the created S3 bucket
    Value: !GetAtt MyS3Bucket.Arn
