AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager Stack - Create application secrets

Parameters:
  Environment:
    Type: String

  AppName:
    Type: String

  # Raw secret JSON passed in from master stack
  SecretValue:
    Type: String
    NoEcho: true
    Description: JSON string of secret key-value pairs

Resources:
  AppSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${Environment}/${AppName}/app
      Description: !Sub Application secrets for ${AppName} in ${Environment}
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: App
          Value: !Ref AppName

Outputs:
  SecretArn:
    Description: Secret ARN
    Value: !Ref AppSecret
    Export:
      Name: !Sub ${AWS::StackName}-SecretArn

  SecretName:
    Description: Secret Name
    Value: !Sub ${Environment}/${AppName}/app
    Export:
      Name: !Sub ${AWS::StackName}-SecretName