name: CD - iac-template

on:
  push:
    branches:
      - dev-i

jobs:
  deploy:
    uses: ops-migration/github_shared_templates/.github/workflows/cd-templates.yml@main
    with:
      environment: "dev"
    secrets:
      github-token: ${{ secrets.PAT_TOKEN }}
