name: CD - iac-template

on:
  push:
    branches:
      - dev-i
    paths:
      - 'iac/aws/us-east-1/**'

jobs:
  deploy:
    uses: ops-migration/github_shared_templates/.github/workflows/cd-templates.yml@main
    with:
      environment: "dev"
      stacks-path: "iac/aws/us-east-1"

